import React, { useEffect, useState } from 'react';

function Reports({ user, token }) {
  const [reports, setReports] = useState([]);
  const [courses, setCourses] = useState([]);
  const [selectedCourse, setSelectedCourse] = useState('');
  const [message, setMessage] = useState('');

  useEffect(() => {
    fetch('/api/reports', { headers: { Authorization: `Bearer ${token}` } })
      .then(res => res.json())
      .then(setReports)
      .catch(() => setMessage('Failed to fetch reports'));
    fetch('/api/courses', { headers: { Authorization: `Bearer ${token}` } })
      .then(res => res.json())
      .then(setCourses);
  }, [token]);

  const filteredReports = selectedCourse
    ? reports.filter(r => r.course === selectedCourse)
    : reports;

  return (
    <div>
      <h2>Reports</h2>
      {message && <div style={{ color: 'red' }}>{message}</div>}
      <div>
        <label>Filter by Course: </label>
        <select value={selectedCourse} onChange={e => setSelectedCourse(e.target.value)}>
          <option value="">All Courses</option>
          {courses.map(c => <option key={c._id} value={c._id}>{c.title}</option>)}
        </select>
      </div>
      <table border="1" cellPadding="6" style={{ marginTop: 16 }}>
        <thead>
          <tr>
            <th>Type</th><th>Course</th><th>Generated By</th><th>Data</th><th>Date</th>
          </tr>
        </thead>
        <tbody>
          {filteredReports.map(r => (
            <tr key={r._id}>
              <td>{r.type}</td>
              <td>{courses.find(c => c._id === r.course)?.title || r.course}</td>
              <td>{r.generatedBy?.name || r.generatedBy}</td>
              <td>{typeof r.data === 'object' ? JSON.stringify(r.data) : r.data}</td>
              <td>{r.createdAt ? new Date(r.createdAt).toLocaleString() : ''}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default Reports; 